### ISSUE TITLE
build jack for osx

### ISSUE THREAD

**Issue by raybellwaves** [conda-forge/jack-feedstock#22]
### Comment:

I'm working on https://github.com/conda-forge/marvin-feedstock/pull/2. I'm trying to get pyaudio built for osx. pyaudio has jack as a dependency therefore i'd like to get jack built for osx.

**Comment by raybellwaves** [comment]
I working on a new recipe.yaml as it's easier to test locally. You can find it [here](https://github.com/raybellwaves/staged-recipes/tree/add-jack). I am testing locally via `pixi run build-linux` and getting:

```
Adding in variants from /opt/conda/conda_build_config.yaml
Adding in variants from /home/conda/staged-recipes-copy/.ci_support/linux64.yaml

 ╭─ Finding outputs from recipe
 │ Found 4 variants
 │ Build variant: jack-1.9.22-py39hcf2b5ce_3
 │ 
 │ ╭────────────────────┬──────────────────╮
 │ │ Variant            ┆ Version          │
 │ ╞════════════════════╪══════════════════╡
 │ │ alsa_lib           ┆ 1.2              │
 │ │ c_compiler         ┆ gcc              │
 │ │ c_compiler_version ┆ 13               │
 │ │ c_stdlib           ┆ sysroot          │
 │ │ c_stdlib_version   ┆ 2.17             │
 │ │ channel_targets    ┆ conda-forge main │
 │ │ python             ┆ 3.9.* *_cpython  │
 │ │ target_platform    ┆ linux-64         │
 │ ╰────────────────────┴──────────────────╯
 │ Build variant: jack-1.9.22-py310h044510c_3
 │ 
 │ ╭────────────────────┬──────────────────╮
 │ │ Variant            ┆ Version          │
 │ ╞════════════════════╪══════════════════╡
 │ │ alsa_lib           ┆ 1.2              │
 │ │ c_compiler         ┆ gcc              │
 │ │ c_compiler_version ┆ 13               │
 │ │ c_stdlib           ┆ sysroot          │
 │ │ c_stdlib_version   ┆ 2.17             │
 │ │ channel_targets    ┆ conda-forge main │
 │ │ python             ┆ 3.10.* *_cpython │
 │ │ target_platform    ┆ linux-64         │
 │ ╰────────────────────┴──────────────────╯
 │ Build variant: jack-1.9.22-py311h91d2dd3_3
 │ 
 │ ╭────────────────────┬──────────────────╮
 │ │ Variant            ┆ Version          │
 │ ╞════════════════════╪══════════════════╡
 │ │ alsa_lib           ┆ 1.2              │
 │ │ c_compiler         ┆ gcc              │
 │ │ c_compiler_version ┆ 13               │
 │ │ c_stdlib           ┆ sysroot          │
 │ │ c_stdlib_version   ┆ 2.17             │
 │ │ channel_targets    ┆ conda-forge main │
 │ │ python             ┆ 3.11.* *_cpython │
 │ │ target_platform    ┆ linux-64         │
 │ ╰────────────────────┴──────────────────╯
 │ Build variant: jack-1.9.22-py312hc1c546f_3
 │ 
 │ ╭────────────────────┬──────────────────╮
 │ │ Variant            ┆ Version          │
 │ ╞════════════════════╪══════════════════╡
 │ │ alsa_lib           ┆ 1.2              │
 │ │ c_compiler         ┆ gcc              │
 │ │ c_compiler_version ┆ 13               │
 │ │ c_stdlib           ┆ sysroot          │
 │ │ c_stdlib_version   ┆ 2.17             │
 │ │ channel_targets    ┆ conda-forge main │
 │ │ python             ┆ 3.12.* *_cpython │
 │ │ target_platform    ┆ linux-64         │
 │ ╰────────────────────┴──────────────────╯
 │
 ╰─────────────────── (took 0 seconds)

 ╭─ Running build for recipe: jack-1.9.22-py39hcf2b5ce_3
 │
 │ ╭─ Fetching source code
 │ │ Validated SHA256 values of the downloaded file!
 │ │ Found valid source cache file.
 │ │ Using extracted directory from cache: /home/conda/staged-recipes/build_artifacts/src_cache/v1_9_22_1e42b9fc
 │ │ Copying source from url: /home/conda/staged-recipes/build_artifacts/src_cache/v1_9_22_1e42b9fc to /home/conda/staged-recipes/build_artifacts/bld/rattler-build_jack_173414203
 │ │ 5/work
 │ │
 │ ╰─────────────────── (took 2 seconds)
 │
 │ ╭─ Resolving environments
 │ │ 
 │ │ Resolving build environment:
 │ │   Platform: linux-64 [__unix=0=0, __linux=6.6.51=0, __glibc=2.34=0, __archspec=1=x86_64]
 │ │   Channels: 
 │ │    - file:///home/conda/staged-recipes/build_artifacts/
 │ │    - file:///home/conda/staged-recipes/build_artifacts/
 │ │    - conda-forge
 │ │   Specs:
 │ │    - gcc_linux-64 13.*
 │ │    - sysroot_linux-64 2.17.*
 │ │    - python 3.9.* *_cpython
 │ │    - pkg-config
 │ │ 
 │ │ ╭─────────────────────────┬───────────┬────────────────────┬─────────────┬────────────╮
 │ │ │ Package                 ┆ Version   ┆ Build              ┆ Channel     ┆ Size       │
 │ │ ╞═════════════════════════╪═══════════╪════════════════════╪═════════════╪════════════╡
 │ │ │ _libgcc_mutex           ┆ 0.1       ┆ conda_forge        ┆ conda-forge ┆ 2.50 KiB   │
 │ │ │ _openmp_mutex           ┆ 4.5       ┆ 2_gnu              ┆ conda-forge ┆ 23.07 KiB  │
 │ │ │ binutils_impl_linux-64  ┆ 2.43      ┆ h4bf12b8_2         ┆ conda-forge ┆ 5.42 MiB   │
 │ │ │ binutils_linux-64       ┆ 2.43      ┆ h4852527_2         ┆ conda-forge ┆ 34.13 KiB  │
 │ │ │ bzip2                   ┆ 1.0.8     ┆ h4bc722e_7         ┆ conda-forge ┆ 246.86 KiB │
 │ │ │ ca-certificates         ┆ 2024.8.30 ┆ hbcca054_0         ┆ conda-forge ┆ 155.28 KiB │
 │ │ │ gcc_impl_linux-64       ┆ 13.3.0    ┆ hfea6d02_1         ┆ conda-forge ┆ 64.34 MiB  │
 │ │ │ gcc_linux-64            ┆ 13.3.0    ┆ hc28eda2_7         ┆ conda-forge ┆ 31.25 KiB  │
 │ │ │ kernel-headers_linux-64 ┆ 3.10.0    ┆ he073ed8_18        ┆ conda-forge ┆ 921.37 KiB │
 │ │ │ ld_impl_linux-64        ┆ 2.43      ┆ h712a8e2_2         ┆ conda-forge ┆ 653.53 KiB │
 │ │ │ libffi                  ┆ 3.4.2     ┆ h7f98852_5         ┆ conda-forge ┆ 56.93 KiB  │
 │ │ │ libgcc                  ┆ 14.2.0    ┆ h77fa898_1         ┆ conda-forge ┆ 828.85 KiB │
 │ │ │ libgcc-devel_linux-64   ┆ 13.3.0    ┆ h84ea5a7_101       ┆ conda-forge ┆ 2.48 MiB   │
 │ │ │ libgcc-ng               ┆ 14.2.0    ┆ h69a702a_1         ┆ conda-forge ┆ 52.87 KiB  │
 │ │ │ libgomp                 ┆ 14.2.0    ┆ h77fa898_1         ┆ conda-forge ┆ 450.19 KiB │
 │ │ │ liblzma                 ┆ 5.6.3     ┆ hb9d3cd8_1         ┆ conda-forge ┆ 108.53 KiB │
 │ │ │ libnsl                  ┆ 2.0.1     ┆ hd590300_0         ┆ conda-forge ┆ 32.62 KiB  │
 │ │ │ libsanitizer            ┆ 13.3.0    ┆ heb74ff8_1         ┆ conda-forge ┆ 3.94 MiB   │
 │ │ │ libsqlite               ┆ 3.47.2    ┆ hee588c1_0         ┆ conda-forge ┆ 853.08 KiB │
 │ │ │ libstdcxx               ┆ 14.2.0    ┆ hc0a3c3a_1         ┆ conda-forge ┆ 3.71 MiB   │
 │ │ │ libuuid                 ┆ 2.38.1    ┆ h0b41bf4_0         ┆ conda-forge ┆ 32.81 KiB  │
 │ │ │ libxcrypt               ┆ 4.4.36    ┆ hd590300_1         ┆ conda-forge ┆ 98.04 KiB  │
 │ │ │ libzlib                 ┆ 1.3.1     ┆ hb9d3cd8_2         ┆ conda-forge ┆ 59.53 KiB  │
 │ │ │ ncurses                 ┆ 6.5       ┆ he02047a_1         ┆ conda-forge ┆ 868.25 KiB │
 │ │ │ openssl                 ┆ 3.4.0     ┆ hb9d3cd8_0         ┆ conda-forge ┆ 2.81 MiB   │
 │ │ │ pkg-config              ┆ 0.29.2    ┆ h4bc722e_1009      ┆ conda-forge ┆ 112.48 KiB │
 │ │ │ python                  ┆ 3.9.21    ┆ h9c0c6dc_1_cpython ┆ conda-forge ┆ 22.53 MiB  │
 │ │ │ readline                ┆ 8.2       ┆ h8228510_1         ┆ conda-forge ┆ 274.86 KiB │
 │ │ │ sysroot_linux-64        ┆ 2.17      ┆ h4a8ded7_18        ┆ conda-forge ┆ 14.78 MiB  │
 │ │ │ tk                      ┆ 8.6.13    ┆ noxft_h4845f30_101 ┆ conda-forge ┆ 3.17 MiB   │
 │ │ │ tzdata                  ┆ 2024b     ┆ hc8b5060_0         ┆ conda-forge ┆ 119.49 KiB │
 │ │ ╰─────────────────────────┴───────────┴────────────────────┴─────────────┴────────────╯
 │ │ 
 │ │ Resolving host environment:
 │ │   Platform: linux-64 [__unix=0=0, __linux=6.6.51=0, __glibc=2.34=0, __archspec=1=x86_64]
 │ │   Channels: 
 │ │    - file:///home/conda/staged-recipes/build_artifacts/
 │ │    - file:///home/conda/staged-recipes/build_artifacts/
 │ │    - conda-forge
 │ │   Specs:
 │ │    - libdb
 │ │    - libopus
 │ │    - portaudio
 │ │    - eigen >=3.1.2
 │ │    - alsa-lib 1.2.*
 │ │    - __glibc >=2.17,<3.0.a0
 │ │    - libgcc >=13
 │ │ 
 │ │ ╭───────────────┬─────────┬─────────────┬─────────────┬────────────╮
 │ │ │ Package       ┆ Version ┆ Build       ┆ Channel     ┆ Size       │
 │ │ ╞═══════════════╪═════════╪═════════════╪═════════════╪════════════╡
 │ │ │ _libgcc_mutex ┆ 0.1     ┆ conda_forge ┆ conda-forge ┆ 2.50 KiB   │
 │ │ │ _openmp_mutex ┆ 4.5     ┆ 2_gnu       ┆ conda-forge ┆ 23.07 KiB  │
 │ │ │ alsa-lib      ┆ 1.2.13  ┆ hb9d3cd8_0  ┆ conda-forge ┆ 547.11 KiB │
 │ │ │ eigen         ┆ 3.4.0   ┆ h00ab1b0_0  ┆ conda-forge ┆ 1.04 MiB   │
 │ │ │ libdb         ┆ 6.2.32  ┆ h9c3ff4c_0  ┆ conda-forge ┆ 23.28 MiB  │
 │ │ │ libgcc        ┆ 14.2.0  ┆ h77fa898_1  ┆ conda-forge ┆ 828.85 KiB │
 │ │ │ libgcc-ng     ┆ 14.2.0  ┆ h69a702a_1  ┆ conda-forge ┆ 52.87 KiB  │
 │ │ │ libgomp       ┆ 14.2.0  ┆ h77fa898_1  ┆ conda-forge ┆ 450.19 KiB │
 │ │ │ libopus       ┆ 1.3.1   ┆ h7f98852_1  ┆ conda-forge ┆ 254.55 KiB │
 │ │ │ libstdcxx     ┆ 14.2.0  ┆ hc0a3c3a_1  ┆ conda-forge ┆ 3.71 MiB   │
 │ │ │ libstdcxx-ng  ┆ 14.2.0  ┆ h4852527_1  ┆ conda-forge ┆ 52.84 KiB  │
 │ │ │ portaudio     ┆ 19.7.0  ┆ hf4617a5_0  ┆ conda-forge ┆ 75.53 KiB  │
 │ │ ╰───────────────┴─────────┴─────────────┴─────────────┴────────────╯
 │ │ 
 │ │ Finalized run dependencies:
 │ │ ╭──────────────────┬──────────────────────────────────────────────────╮
 │ │ │ Name             ┆ Spec                                             │
 │ │ ╞══════════════════╪══════════════════════════════════════════════════╡
 │ │ │ Run dependencies ┆                                                  │
 │ │ │ libdb            ┆                                                  │
 │ │ │ __glibc          ┆ >=2.17,<3.0.a0 (RE of [build: sysroot_linux-64]) │
 │ │ │ libgcc           ┆ >=13 (RE of [build: gcc_linux-64])               │
 │ │ │ libdb            ┆ >=6.2.32,<6.3.0a0 (RE of [host: libdb])          │
 │ │ │ portaudio        ┆ >=19.7.0,<19.8.0a0 (RE of [host: portaudio])     │
 │ │ │ libopus          ┆ >=1.3.1,<2.0a0 (RE of [host: libopus])           │
 │ │ │ alsa-lib         ┆ >=1.2.13,<1.3.0a0 (RE of [host: alsa-lib])       │
 │ │ ╰──────────────────┴──────────────────────────────────────────────────╯
 │ │
 │ ╰─────────────────── (took 21 seconds)
 │ 
 │ Installing build environment
 │ ✔ validate cache       31 packages in 34ms
 │   installing packages  [00:00:04] [━━━━━━━━━━━━━━━━━━━━]    31/31 gcc_impl_linux-64 (+21)                                                                                       │
 ╰─────────────────── (took 28 seconds)
Error: 
  × Failed to resolve dependencies: failed to link ncurses-6.5-he02047a_1.conda
  ├─▶ failed to link ncurses-6.5-he02047a_1.conda
  ├─▶ failed to link 'share/terminfo/n/ncr260vt300wpp'
  ├─▶ failed to copy file to destination
  ╰─▶ Too many levels of symbolic links (os error 40)

Traceback (most recent call last):
  File "/home/conda/staged-recipes-copy/.ci_support/build_all.py", line 356, in <module>
    build_all(os.path.join(root_dir, "recipes"), args.arch)
  File "/home/conda/staged-recipes-copy/.ci_support/build_all.py", line 192, in build_all
    build_folders_rattler_build(recipes_dir, platform, arch, channel_urls)
  File "/home/conda/staged-recipes-copy/.ci_support/build_all.py", line 292, in build_folders_rattler_build
    subprocess.run(args + ["--variant-config", fp.name], check=True)
  File "/opt/conda/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['rattler-build', 'build', '--recipe-dir', '/home/conda/staged-recipes-copy/recipes', '--target-platform', 'linux-64', '-c', '/home/conda/staged-recipes/build_artifacts', '-c', 'conda-forge', '--variant-config', '/tmp/tmpues46klr']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/Users/raybell/Documents/PYTHON_dev/tmp3/staged-recipes/build-locally.py", line 115, in <module>
    main()
  File "/Users/raybell/Documents/PYTHON_dev/tmp3/staged-recipes/build-locally.py", line 107, in main
    run_docker_build(ns)
  File "/Users/raybell/Documents/PYTHON_dev/tmp3/staged-recipes/build-locally.py", line 39, in run_docker_build
    subprocess.check_call([script])
  File "/Users/raybell/Documents/PYTHON_dev/tmp3/staged-recipes/.pixi/envs/linux/lib/python3.12/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['.scripts/run_docker_build.sh']' returned non-zero exit status 1.
```

**Comment by h-vetinari** [comment]
ncurses unfortunately requires a case-sensitive filesystem: https://github.com/conda-forge/ncurses-feedstock/issues/73

It's possible that some part of the symlink resolution does not respect cases correctly. Personally, I think the ncurses we ship should be changed to not contain collisions on case-insensitive filesystems.

**Comment by wolfv** [comment]
@h-vetinari if I look at ncurses correclty, then we don't ship case sensitive files on macOS, but our Linux builds still contain them whcih makes cross-compilation difficult.

**Comment by raybellwaves** [comment]
closed viahttps ://github.com/conda-forge/jack-feedstock/pull/24
